  export 'package:flutter/services.dart';
  export 'package:flutter/material.dart';
  export 'package:splash_screen_view/SplashScreenView.dart';
  export 'package:flutter_bloc/flutter_bloc.dart';
  export 'package:myapp/src/teta_files/theme_cubit.dart';
  export 'package:myapp/src/teta_files/app_locale.dart';
  export 'package:flutter_translator/flutter_translator.dart';
  export 'package:teta_cms/teta_cms.dart';
  export 'package:sizer/sizer.dart';
  export 'package:supabase/supabase.dart' hide RealtimeSubscription;
  export 'package:supabase_flutter/supabase_flutter.dart' hide RealtimeSubscription;
  export 'package:universal_platform/universal_platform.dart';
  export 'package:cross_file/cross_file.dart';
  export 'package:google_fonts/google_fonts.dart';
  export 'package:collection/collection.dart';
  export 'package:myapp/src/teta_files/teta_theme.dart';
  export 'package:myapp/src/pages/index.dart';
  export 'package:myapp/src/components/index.dart';
  export 'package:material_design_icons_flutter/material_design_icons_flutter.dart';
  export 'package:flutter_translator/flutter_translator.dart';
  export 'package:in_app_review/in_app_review.dart';
  export 'package:url_launcher/url_launcher.dart';
  export 'package:share/share.dart';
  export 'package:responsive_builder/responsive_builder.dart' hide WidgetBuilder;
  export 'package:uni_links/uni_links.dart';
  export 'package:myapp/src/teta_files/mixpanel.dart';
  export 'package:url_launcher/url_launcher_string.dart';
  export 'package:myapp/src/teta_files/firebase_messaging.dart';
export 'package:myapp/src/teta_files/local_notification_services.dart';

  