  name: myapp
  description: A new Teta Flutter project.
  publish_to: 'none'
  version: 1.0.0+1
  environment:
    sdk: ">=2.12.0 <3.0.0"
  dependencies:
    flutter:
      sdk: flutter
    teta_cms:
    google_fonts: 2.1.0  
    supabase: 0.3.4+1
    supabase_flutter: 0.3.1+3
    clipboard: 0.1.3
    http: 0.13.5
    splash_screen_view: 3.0.0
    sizer: ^2.0.15
    flutter_bloc: 7.3.3
    hive: 2.2.2
    hive_flutter: 1.1.0
    flutter_translator: ^0.1.7
    cross_file: 0.3.3+1
    universal_platform: ^1.0.0+1
    material_design_icons_flutter: 5.0.6595
    in_app_review: ^2.0.4
    share: ^2.0.4
    responsive_builder: ^0.4.3
    uni_links: ^0.5.1
    url_launcher: ^6.1.6
    flutter_stripe: 5.0.0
    purchases_flutter: 3.10.0
    
    mixpanel_flutter: ^2.0.0
    
    dart_airtable: 1.1.0
    firebase_core: ^2.4.0
    firebase_analytics: ^10.0.7
    firebase_messaging: ^14.1.4
    flutter_local_notifications: ^12.0.4
    flutter_staggered_animations: 1.0.0
    bouncing_widget: 2.0.0
    google_mobile_ads: 1.2.0
    font_awesome_flutter_named: 1.1.1
    webviewx: 0.2.1
  dependency_overrides:
    platform: 3.1.0

  dev_dependencies:
    flutter_test:
      sdk: flutter
    flutter_lints: 2.0.0

  flutter:
    uses-material-design: true
    assets:
      - assets/teta-app.png
  